name: Publish to GitHub Packages
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Execute Gradle build
        run: ./gradlew :leviathan:check
      - name: Execute Gradle build
        run: ./gradlew :leviathan:publish -Ppublish.user=${{secrets.PUBLISH_USER}} -Ppublish.key=${{secrets.PUBLISH_KEY}} 
